// rent_a_car/client/react-app/rent-a-car-react/src/components/add-car/AddCarComponent.js
import React, { Component } from "react";
import carService from "../../service/car.service";
import { Link } from "react-router-dom";
import "./addCar.css";

import { createBrowserHistory } from "history";

const history = createBrowserHistory();

class AddCarComponent extends Component {
  constructor(props) {
    super(props);

    this.state = {
      car: {
        model: "",
        brand: "",
        year: "",
        doors: "",
        price: "",
        seats: "",
        isAvailable: "",
        rentedBy: "",
        location: "",
        imageUrl: "",
      },
    };

    this.handleChange = this.handleChange.bind(this);
    this.addCar = this.addCar.bind(this);
  }

  handleChange(event) {
    const { name, value } = event.target;
    const { car } = this.state;
    this.setState({
      car: {
        ...car,
        [name]: value,
      },
    });
  }

  addCar() {
    const { car } = this.state;
    if (
      car.model &&
      car.brand &&
      car.year &&
      car.doors &&
      car.price &&
      car.seats &&
      car.isAvailable &&
      car.imageUrl
    ) {
      carService.addCar(car);
      history.push("/view-cars");
    }
  }

  render() {
    const { car } = this.state;
    return (
      <div className="page-wrapper bg p-t-180 p-b-100 font-robo">
        <div className="wrapper wrapper--w960">
          <div>
            <div id="form-div">
              <h2 className="title">Add Car</h2>
              <form id="carsForm">
                <div id="input-field-div">
                  <input
                    className="input"
                    type="text"
                    name="brand"
                    placeholder="Brand"
                    value={car.brand}
                    onChange={this.handleChange}
                  />
                </div>
                <div>
                  <input
                    className="input"
                    type="text"
                    name="model"
                    placeholder="Model"
                    value={car.model}
                    onChange={this.handleChange}
                  />
                </div>
                <div>
                  <input
                    className="input"
                    type="text"
                    name="year"
                    placeholder="Year"
                    value={car.year}
                    onChange={this.handleChange}
                  />
                </div>
                <div>
                  <input
                    className="input"
                    type="text"
                    name="seats"
                    placeholder="Seats"
                    value={car.seats}
                    onChange={this.handleChange}
                  />
                </div>
                <div>
                  <input
                    className="input"
                    type="text"
                    name="doors"
                    placeholder="Doors"
                    value={car.doors}
                    onChange={this.handleChange}
                  />
                </div>
                <div>
                  <input
                    className="input"
                    type="text"
                    placeholder="Is available"
                    name="isAvailable"
                    value={car.isAvailable}
                    onChange={this.handleChange}
                  />
                </div>
                <div>
                  <input
                    className="input"
                    type="text"
                    placeholder="Price"
                    name="price"
                    value={car.price}
                    onChange={this.handleChange}
                  />
                </div>
                <div>
                  <input
                    type="text"
                    className="input"
                    placeholder="Location"
                    name="location"
                    value={car.location}
                    onChange={this.handleChange}
                  />
                </div>
                <div>
                  <input
                    className="input"
                    type="text"
                    placeholder="Image url"
                    name="imageUrl"
                    value={car.imageUrl}
                    onChange={this.handleChange}
                  />
                </div>
                <div className="form-group">
                  <div className="p-t-30">
                    <button
                      className="btn btn--radius btn--green"
                      type="submit"
                      onClick={this.addCar}
                    >
                      Add car
                    </button>

                    <Link to="/login" className="btn btn-primary">
                      Cancel
                    </Link>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
export default AddCarComponent;

// Angular_Project/src/app/add-car/add-car.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';
import { CarService } from '../service/cars/car.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-add-car',
  templateUrl: './add-car.component.html',
  styleUrls: ['./add-car.component.scss']
})
export class AddCarComponent implements OnInit {

  constructor(private carService:CarService, private route:Router) { }


  carsForm = new FormGroup({
    model: new FormControl(''),
    price: new FormControl(''),
    seats: new FormControl(''),
    role: new FormControl(''),
    doors:new FormControl(''),
    automatic: new FormControl(''),
    airConditioning: new FormControl(''),
    available: new FormControl(''),
    imageURL: new FormControl(''),
    location: new FormControl(''),
  });
  

  ngOnInit() {
  }

  sumbitData(){
    var model = this.carsForm.get("model").value;
    var price = this.carsForm.get("price").value;
    var seats = this.carsForm.get("seats").value;
    var doors = this.carsForm.get("doors").value;
    var automatic =  this.carsForm.get("automatic").value;
    var airConditioning =  this.carsForm.get("airConditioning").value;
    var available =  this.carsForm.get("available").value;
    var imageURL =  this.carsForm.get("imageURL").value;
    var location =  this.carsForm.get("location").value;


    var result = this.carService.addCar(model, price, seats, doors, automatic, airConditioning, available, imageURL
      , location)
    .then(result => { if(result!="" && result!=null) {this.route.navigateByUrl("/admin"); window.location.reload;} 
                      });

    console.log(result);

  
  }

}
interface Car {
  id: string;
  model: string;
  price: number;
  seats: number;
  doors: number;
  automatic: boolean;
  airConditioning: boolean;
  available: boolean;
  imageURL: string;
  location: string;


}

<div class="page-wrapper bg p-t-180 p-b-100 font-robo">
        <div class="wrapper wrapper--w960">
            <div class="card card-2">
                <div class="card-heading"></div>
                <div class="card-body">
                    <h2 class="title">Add Cars</h2>
                    <form [formGroup]="carsForm">

                        <div class="input-group">
                            <input class="input--style-2" type="text" placeholder="Model" formControlName="model">
                        </div>
                        <div class="input-group">
                            <input class="input--style-2" type="number" step="any" placeholder="Price" formControlName="price">
                        </div>
                        <div class="input-group">
                            <input class="input--style-2" type="number" placeholder="Seats" formControlName="seats">
                        </div>

                        <div class="input-group">
                                <input class="input--style-2" type="number" placeholder="Doors" formControlNameme="doors">
                            </div>
                       
                        <div class="input-group">
                            <input class="input--style-2" type="text" placeholder="Automatic - true or false" formControlName="automatic">
                        </div>

                        <div class="input-group">
                                <input class="input--style-2" type="text" placeholder="Image URL" formControlName="imageURL">
                        </div>

                        <div class="input-group">
                                <input class="input--style-2" type="text" placeholder="Location" formControlName="location">
                        </div>

                        <div class="p-t-30">
                            <button class="btn btn--radius btn--green" type="submit" (click)="sumbitData()">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
